/** @type {import('tailwindcss').Config} */

module.exports = {
  content: ["./app/**/*.{js,jsx,ts,tsx}", "./components/**/*.{js,jsx,ts,tsx}", "./src/**/*.{html,js}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {

        primary: {
          DEFAULT: "#00a859",
          100: "#ccf2e0",
          200: "#99e6b3",
          300: "#66db8f",
          400: "#33d66a",
          500: "#00a859",
          600: "#009a51",
          700: "#008a4a",
          800: "#007a43",
          900: "#006a3c",
        },
        secondary: {
          DEFAULT: "#fdcd11",
          100: "#fef6d8",
          200: "#fdf0a5",
          300: "#fce77f",
          400: "#fcd95a",
          500: "#fdcd11",
          600: "#fbc50e",
          700: "#f9bc0b",
          800: "#f8b108",
          900: "#f7a505",
          950: "#c2c2c2"
        },
        accent: { DEFAULT: "#0f613f" },
        gray: {
          DEFAULT: "#fdfdfd",
          defaultSubtle: "#f4f4f4",
          disabled: "#232533",
          borderDefault: "#d1d1d1",
          borderDisabled: "#eeeeee",
          textTitle: "#353535",
          textBody: "#7b7b7b",
          textSubtitle: "#4e4e4e",
          textCaption: "#c2c2c2",
          textNegative: "#fdfdfd",
          textDisabled: "#a4a4a4",
        },
        
        error: {
          DEFAULT: "#ff0000",
          defaultSubtle: "#ffe6e6",
          defaultLight: "#ff5454",
          defaultDark: "#b50000",
          borderDefault: "#e80000",
          borderDefaultLight: "#ff3333",
          borderDefaultDark: "#8c0000",
          textLink: "#e80000",
        },
        success: {
          DEFAULT: "#34c759",
          defaultSubtle: "#ebf9ee",
          defaultLight: "#77b990",
          defaultDark: "#258d3f",
          borderDefault: "#2fb551",
          borderDefaultLight: "#5dd27a",
          borderDefaultDark: "#1d6d31",
          textLink: "#2fb551",
        },
      },
      fontFamily: {
        "SpaceGrotesk-Light": ['"SpaceGrotesk-Light"', "sans-serif"],
        "SpaceGrotesk-Regular": ['"SpaceGrotesk"', "sans-serif"],
        "SpaceGrotesk-Medium": ['"SpaceGrotesk-Medium"', "sans-serif"],
        "SpaceGrotesk-Semibold": ['"SpaceGrotesk-SemiBold"', "sans-serif"],
        "SpaceGrotesk-Bold": ['"SpaceGrotesk-Bold"', "sans-serif"],
        
        "Raleway-Thin": ["Raleway-Thin", "sans-serif"],
        "Raleway-ThinItalic": ["Raleway-ThinItalic", "sans-serif"],
        "Raleway-Extralight": ["Raleway-ExtraLight", "sans-serif"],
        "Raleway-ExtralightItalic": ["Raleway-ExtraLightItalic", "sans-serif"],
        "Raleway-Light": ["Raleway-Light", "sans-serif"],
        "Raleway-LightItalic": ["Raleway-LightItalic", "sans-serif"],
        "Raleway-Regular": ["Raleway-Regular", "sans-serif"],
        "Raleway-Italic": ["Raleway-Italic", "sans-serif"], // Regular Italic
        "Raleway-Medium": ["Raleway-Medium", "sans-serif"],
        "Raleway-MediumItalic": ["Raleway-MediumItalic", "sans-serif"],
        "Raleway-SemiBold": ["Raleway-SemiBold", "sans-serif"],
        "Raleway-SemiBoldItalic": ["Raleway-SemiBoldItalic", "sans-serif"],
        "Raleway-Bold": ["Raleway-Bold", "sans-serif"],
        "Raleway-BoldItalic": ["Raleway-BoldItalic", "sans-serif"],
        "Raleway-ExtraBold": ["Raleway-ExtraBold", "sans-serif"],
        "Raleway-ExtraBoldItalic": ["Raleway-ExtraBoldItalic", "sans-serif"],
        "Raleway-Black": ["Raleway-Black", "sans-serif"],
        "Raleway-BlackItalic": ["Raleway-BlackItalic", "sans-serif"],
      },
    },
  },
  plugins: [],
};
